CREATE TABLE IF NOT EXISTS FRUITS(
    NAME TEXT,
    BATCH_NO INT,
    PRICE INT
);

INSERT INTO FRUITS VALUES
('APPLE', 201, 300),
('ORANGE', 202, 100),
('BANANA', 203, 400),
('CHERRY', 204, 200),
('GRAPE', 205, 500),
('APPLE', 201, 300),
('CHERRY', 204, 200),
('STRAWBERRY', 206, 800),
('AVOCADO', 207, 1000);

SELECT DISTINCT NAME FROM FRUITS;

SELECT COUNT(NAME) AS Apple_sold FROM FRUITS
WHERE NAME = "APPLE";

SELECT COUNT(BATCH_NO) AS Total_fruits_sold FROM FRUITS;

SELECT SUM(PRICE) AS Total_sales
FROM FRUITS;

SELECT AVG(PRICE) AS Average_price
FROM FRUITS;