CREATE TABLE IF NOT EXISTS PRODUCTS(
    ID INT,
    NAME TEXT,
    PRICE INT
);
INSERT INTO PRODUCTS VALUES
(101, 'RAM', 100),
(101, 'RAM', 100),
(104, 'CPU', 180),
(103, 'MONITOR', 90),
(106, 'KEYBOARD', 50),
(104, 'CPU', 180),
(101, 'RAM', 100);

SELECT DISTINCT NAME FROM PRODUCTS;

SELECT COUNT(ID) AS Items_sold FROM PRODUCTS;

SELECT COUNT(NAME) AS Ram_sold FROM PRODUCTS WHERE NAME = "RAM";

SELECT SUM(PRICE) AS Total_Sales
FROM PRODUCTS;

SELECT AVG(PRICE) AS Average_Price
FROM PRODUCTS;

SELECT AVG(PRICE) AS Average_RAM_Price
FROM PRODUCTS WHERE NAME = "RAM";

--DISTINCT ALLOWS YOU TO SELECT ONE ITEM IN DUPLICATE LIST
--COUNT ALLOWS YOU TO SELECT A PARTICULAR COLUMN TO COUNT