#r = read, w = write (and it removes everything, it can also open a new txt file), a = append
moses = open("moses.txt", "r")
print(moses.read())
moses.close()
moses = open("moses.txt", "w")
moses.write("I am into python")
moses.close()
moses = open("moses.txt", "a")
moses.write("I love solving problems also")
moses.close()
#After class project
file = open("file.txt", "w")
file.write("I love python")
file.close()
file = open("file.txt", "r")
print(file.read())
file.close()