CREATE TABLE IF NOT EXISTS STUDENTS(
    NAME TEXT,
    AGE INTEGER,
    GRADE VARCHAR(20),
    CITY TEXT
);

INSERT INTO STUDENTS VALUES
("MOSES", 18, "12", "LAGOS"),
("MHUBBY", 12, "7", "CANADA"),
("MARY", 6, "4", "LAGOS"),
("MAX", 19, "12", "NEW YORK"),
("MICHEAL", 15, "10", "LAGOS");

SELECT NAME FROM STUDENTS
WHERE NAME LIKE "M%" AND CITY = "LAGOS" AND AGE = 12 OR GRADE = 12;
